'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsCotacao
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FachadaWSSGSSoapBinding", [Namespace]:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
    Partial Public Class FachadaWSSGSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getValoresSeriesVOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getUltimosValoresSerieVOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getValoresSeriesXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getUltimoValorVOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getUltimoValorXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getValorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getValorEspecialOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Sistema_Lonas.My.MySettings.Default.Sistema_Lonas_br_gov_bcb_www3_FachadaWSSGSService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getValoresSeriesVOCompleted As getValoresSeriesVOCompletedEventHandler
        
        '''<remarks/>
        Public Event getUltimosValoresSerieVOCompleted As getUltimosValoresSerieVOCompletedEventHandler
        
        '''<remarks/>
        Public Event getValoresSeriesXMLCompleted As getValoresSeriesXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event getUltimoValorVOCompleted As getUltimoValorVOCompletedEventHandler
        
        '''<remarks/>
        Public Event getUltimoValorXMLCompleted As getUltimoValorXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event getValorCompleted As getValorCompletedEventHandler
        
        '''<remarks/>
        Public Event getValorEspecialCompleted As getValorEspecialCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getValoresSeriesVO(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As <System.Xml.Serialization.SoapElementAttribute("getValoresSeriesVOReturn")> WSSerieVO()
            Dim results() As Object = Me.Invoke("getValoresSeriesVO", New Object() {in0, in1, in2})
            Return CType(results(0),WSSerieVO())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getValoresSeriesVOAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String)
            Me.getValoresSeriesVOAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getValoresSeriesVOAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String, ByVal userState As Object)
            If (Me.getValoresSeriesVOOperationCompleted Is Nothing) Then
                Me.getValoresSeriesVOOperationCompleted = AddressOf Me.OngetValoresSeriesVOOperationCompleted
            End If
            Me.InvokeAsync("getValoresSeriesVO", New Object() {in0, in1, in2}, Me.getValoresSeriesVOOperationCompleted, userState)
        End Sub
        
        Private Sub OngetValoresSeriesVOOperationCompleted(ByVal arg As Object)
            If (Not (Me.getValoresSeriesVOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getValoresSeriesVOCompleted(Me, New getValoresSeriesVOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getUltimosValoresSerieVO(ByVal in0 As Long, ByVal in1 As Long) As <System.Xml.Serialization.SoapElementAttribute("getUltimosValoresSerieVOReturn")> WSSerieVO
            Dim results() As Object = Me.Invoke("getUltimosValoresSerieVO", New Object() {in0, in1})
            Return CType(results(0),WSSerieVO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getUltimosValoresSerieVOAsync(ByVal in0 As Long, ByVal in1 As Long)
            Me.getUltimosValoresSerieVOAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getUltimosValoresSerieVOAsync(ByVal in0 As Long, ByVal in1 As Long, ByVal userState As Object)
            If (Me.getUltimosValoresSerieVOOperationCompleted Is Nothing) Then
                Me.getUltimosValoresSerieVOOperationCompleted = AddressOf Me.OngetUltimosValoresSerieVOOperationCompleted
            End If
            Me.InvokeAsync("getUltimosValoresSerieVO", New Object() {in0, in1}, Me.getUltimosValoresSerieVOOperationCompleted, userState)
        End Sub
        
        Private Sub OngetUltimosValoresSerieVOOperationCompleted(ByVal arg As Object)
            If (Not (Me.getUltimosValoresSerieVOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getUltimosValoresSerieVOCompleted(Me, New getUltimosValoresSerieVOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getValoresSeriesXML(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String) As <System.Xml.Serialization.SoapElementAttribute("getValoresSeriesXMLReturn")> String
            Dim results() As Object = Me.Invoke("getValoresSeriesXML", New Object() {in0, in1, in2})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getValoresSeriesXMLAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String)
            Me.getValoresSeriesXMLAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getValoresSeriesXMLAsync(ByVal in0() As Long, ByVal in1 As String, ByVal in2 As String, ByVal userState As Object)
            If (Me.getValoresSeriesXMLOperationCompleted Is Nothing) Then
                Me.getValoresSeriesXMLOperationCompleted = AddressOf Me.OngetValoresSeriesXMLOperationCompleted
            End If
            Me.InvokeAsync("getValoresSeriesXML", New Object() {in0, in1, in2}, Me.getValoresSeriesXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OngetValoresSeriesXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getValoresSeriesXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getValoresSeriesXMLCompleted(Me, New getValoresSeriesXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getUltimoValorVO(ByVal in0 As Long) As <System.Xml.Serialization.SoapElementAttribute("getUltimoValorVOReturn")> WSSerieVO
            Dim results() As Object = Me.Invoke("getUltimoValorVO", New Object() {in0})
            Return CType(results(0),WSSerieVO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getUltimoValorVOAsync(ByVal in0 As Long)
            Me.getUltimoValorVOAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getUltimoValorVOAsync(ByVal in0 As Long, ByVal userState As Object)
            If (Me.getUltimoValorVOOperationCompleted Is Nothing) Then
                Me.getUltimoValorVOOperationCompleted = AddressOf Me.OngetUltimoValorVOOperationCompleted
            End If
            Me.InvokeAsync("getUltimoValorVO", New Object() {in0}, Me.getUltimoValorVOOperationCompleted, userState)
        End Sub
        
        Private Sub OngetUltimoValorVOOperationCompleted(ByVal arg As Object)
            If (Not (Me.getUltimoValorVOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getUltimoValorVOCompleted(Me, New getUltimoValorVOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getUltimoValorXML(ByVal in0 As Long) As <System.Xml.Serialization.SoapElementAttribute("getUltimoValorXMLReturn")> String
            Dim results() As Object = Me.Invoke("getUltimoValorXML", New Object() {in0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getUltimoValorXMLAsync(ByVal in0 As Long)
            Me.getUltimoValorXMLAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getUltimoValorXMLAsync(ByVal in0 As Long, ByVal userState As Object)
            If (Me.getUltimoValorXMLOperationCompleted Is Nothing) Then
                Me.getUltimoValorXMLOperationCompleted = AddressOf Me.OngetUltimoValorXMLOperationCompleted
            End If
            Me.InvokeAsync("getUltimoValorXML", New Object() {in0}, Me.getUltimoValorXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OngetUltimoValorXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getUltimoValorXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getUltimoValorXMLCompleted(Me, New getUltimoValorXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getValor(ByVal in0 As Long, ByVal in1 As String) As <System.Xml.Serialization.SoapElementAttribute("getValorReturn")> Decimal
            Dim results() As Object = Me.Invoke("getValor", New Object() {in0, in1})
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getValorAsync(ByVal in0 As Long, ByVal in1 As String)
            Me.getValorAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getValorAsync(ByVal in0 As Long, ByVal in1 As String, ByVal userState As Object)
            If (Me.getValorOperationCompleted Is Nothing) Then
                Me.getValorOperationCompleted = AddressOf Me.OngetValorOperationCompleted
            End If
            Me.InvokeAsync("getValor", New Object() {in0, in1}, Me.getValorOperationCompleted, userState)
        End Sub
        
        Private Sub OngetValorOperationCompleted(ByVal arg As Object)
            If (Not (Me.getValorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getValorCompleted(Me, New getValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", ResponseNamespace:="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS")>  _
        Public Function getValorEspecial(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String) As <System.Xml.Serialization.SoapElementAttribute("getValorEspecialReturn")> Decimal
            Dim results() As Object = Me.Invoke("getValorEspecial", New Object() {in0, in1, in2})
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getValorEspecialAsync(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String)
            Me.getValorEspecialAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getValorEspecialAsync(ByVal in0 As Long, ByVal in1 As String, ByVal in2 As String, ByVal userState As Object)
            If (Me.getValorEspecialOperationCompleted Is Nothing) Then
                Me.getValorEspecialOperationCompleted = AddressOf Me.OngetValorEspecialOperationCompleted
            End If
            Me.InvokeAsync("getValorEspecial", New Object() {in0, in1, in2}, Me.getValorEspecialOperationCompleted, userState)
        End Sub
        
        Private Sub OngetValorEspecialOperationCompleted(ByVal arg As Object)
            If (Not (Me.getValorEspecialCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getValorEspecialCompleted(Me, New getValorEspecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")>  _
    Partial Public Class WSSerieVO
        
        Private anoFimField As Integer
        
        Private anoInicioField As Integer
        
        Private avisoField As String
        
        Private diaFimField As Integer
        
        Private diaInicioField As Integer
        
        Private especialField As Boolean
        
        Private fonteField As String
        
        Private fullNameField As String
        
        Private gestorProprietarioField As String
        
        Private mesFimField As Integer
        
        Private mesInicioField As Integer
        
        Private nomeAbreviadoField As String
        
        Private nomeCompletoField As String
        
        Private oidField As Long
        
        Private periodicidadeField As String
        
        Private periodicidadeSiglaField As String
        
        Private possuiBloqueiosField As Boolean
        
        Private publicaField As Boolean
        
        Private shortNameField As String
        
        Private ultimoValorField As WSValorSerieVO
        
        Private unidadePadraoField As String
        
        Private unidadePadraoInglesField As String
        
        Private valorDiaNaoUtilField As Boolean
        
        Private valoresField() As WSValorSerieVO
        
        '''<remarks/>
        Public Property anoFim() As Integer
            Get
                Return Me.anoFimField
            End Get
            Set
                Me.anoFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property anoInicio() As Integer
            Get
                Return Me.anoInicioField
            End Get
            Set
                Me.anoInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property aviso() As String
            Get
                Return Me.avisoField
            End Get
            Set
                Me.avisoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaFim() As Integer
            Get
                Return Me.diaFimField
            End Get
            Set
                Me.diaFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaInicio() As Integer
            Get
                Return Me.diaInicioField
            End Get
            Set
                Me.diaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property especial() As Boolean
            Get
                Return Me.especialField
            End Get
            Set
                Me.especialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fonte() As String
            Get
                Return Me.fonteField
            End Get
            Set
                Me.fonteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fullName() As String
            Get
                Return Me.fullNameField
            End Get
            Set
                Me.fullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gestorProprietario() As String
            Get
                Return Me.gestorProprietarioField
            End Get
            Set
                Me.gestorProprietarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesFim() As Integer
            Get
                Return Me.mesFimField
            End Get
            Set
                Me.mesFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesInicio() As Integer
            Get
                Return Me.mesInicioField
            End Get
            Set
                Me.mesInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nomeAbreviado() As String
            Get
                Return Me.nomeAbreviadoField
            End Get
            Set
                Me.nomeAbreviadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nomeCompleto() As String
            Get
                Return Me.nomeCompletoField
            End Get
            Set
                Me.nomeCompletoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oid() As Long
            Get
                Return Me.oidField
            End Get
            Set
                Me.oidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property periodicidade() As String
            Get
                Return Me.periodicidadeField
            End Get
            Set
                Me.periodicidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property periodicidadeSigla() As String
            Get
                Return Me.periodicidadeSiglaField
            End Get
            Set
                Me.periodicidadeSiglaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property possuiBloqueios() As Boolean
            Get
                Return Me.possuiBloqueiosField
            End Get
            Set
                Me.possuiBloqueiosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property publica() As Boolean
            Get
                Return Me.publicaField
            End Get
            Set
                Me.publicaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property shortName() As String
            Get
                Return Me.shortNameField
            End Get
            Set
                Me.shortNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ultimoValor() As WSValorSerieVO
            Get
                Return Me.ultimoValorField
            End Get
            Set
                Me.ultimoValorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidadePadrao() As String
            Get
                Return Me.unidadePadraoField
            End Get
            Set
                Me.unidadePadraoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property unidadePadraoIngles() As String
            Get
                Return Me.unidadePadraoInglesField
            End Get
            Set
                Me.unidadePadraoInglesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property valorDiaNaoUtil() As Boolean
            Get
                Return Me.valorDiaNaoUtilField
            End Get
            Set
                Me.valorDiaNaoUtilField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property valores() As WSValorSerieVO()
            Get
                Return Me.valoresField
            End Get
            Set
                Me.valoresField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")>  _
    Partial Public Class WSValorSerieVO
        
        Private anoField As Integer
        
        Private anoFimField As Integer
        
        Private bloqueadoField As Boolean
        
        Private bloqueioLiberadoField As Boolean
        
        Private diaField As Integer
        
        Private diaFimField As Integer
        
        Private mesField As Integer
        
        Private mesFimField As Integer
        
        Private oidField As Long
        
        Private oidSerieField As Long
        
        Private svalorField As String
        
        Private valorField As System.Nullable(Of Decimal)
        
        '''<remarks/>
        Public Property ano() As Integer
            Get
                Return Me.anoField
            End Get
            Set
                Me.anoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property anoFim() As Integer
            Get
                Return Me.anoFimField
            End Get
            Set
                Me.anoFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bloqueado() As Boolean
            Get
                Return Me.bloqueadoField
            End Get
            Set
                Me.bloqueadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bloqueioLiberado() As Boolean
            Get
                Return Me.bloqueioLiberadoField
            End Get
            Set
                Me.bloqueioLiberadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dia() As Integer
            Get
                Return Me.diaField
            End Get
            Set
                Me.diaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property diaFim() As Integer
            Get
                Return Me.diaFimField
            End Get
            Set
                Me.diaFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mes() As Integer
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mesFim() As Integer
            Get
                Return Me.mesFimField
            End Get
            Set
                Me.mesFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oid() As Long
            Get
                Return Me.oidField
            End Get
            Set
                Me.oidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oidSerie() As Long
            Get
                Return Me.oidSerieField
            End Get
            Set
                Me.oidSerieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property svalor() As String
            Get
                Return Me.svalorField
            End Get
            Set
                Me.svalorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property valor() As System.Nullable(Of Decimal)
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getValoresSeriesVOCompletedEventHandler(ByVal sender As Object, ByVal e As getValoresSeriesVOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getValoresSeriesVOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WSSerieVO()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WSSerieVO())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getUltimosValoresSerieVOCompletedEventHandler(ByVal sender As Object, ByVal e As getUltimosValoresSerieVOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getUltimosValoresSerieVOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WSSerieVO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WSSerieVO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getValoresSeriesXMLCompletedEventHandler(ByVal sender As Object, ByVal e As getValoresSeriesXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getValoresSeriesXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")> _
    Public Delegate Sub getUltimoValorVOCompletedEventHandler(ByVal sender As Object, ByVal e As getUltimoValorVOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getUltimoValorVOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WSSerieVO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WSSerieVO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getUltimoValorXMLCompletedEventHandler(ByVal sender As Object, ByVal e As getUltimoValorXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getUltimoValorXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getValorCompletedEventHandler(ByVal sender As Object, ByVal e As getValorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getValorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getValorEspecialCompletedEventHandler(ByVal sender As Object, ByVal e As getValorEspecialCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getValorEspecialCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
    End Class
End Namespace
